FROM node:20.17.0-alpine

WORKDIR /app

COPY package*.json ./

#Install dependencies (npm ci ensures a clean install)
RUN npm install

COPY . .

# Expose the port that the app will run on
EXPOSE 3000

CMD ["npm", "run", "dev"]
