---
- name: Configure Nginx with Let's Encrypt SSL
  hosts: webserver
  become: yes
  # vars:
  #   domain_name: "ec2-13-210-47-135.ap-southeast-2.compute.amazonaws.com"
  #   email: "123@example.com"
  #   web_root: "/home/ubuntu/easy-tax"
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    # - name: Start and enable Nginx service
    #   systemd:
    #     name: nginx
    #     state: started
    #     enabled: yes

    - name: Copy Nginx configuration
      template:
        src: nginxconfig.j2
        dest: /etc/nginx/sites-available/nextjs
      notify:
        - restart nginx

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create symlink for the site
      file:
        src: /etc/nginx/sites-available/nextjs
        dest: /etc/nginx/sites-enabled/nextjs
        state: link

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
